// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for FillTableFunction
 */
export interface FillTableFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/Construct/lambda/fillTable.
 */
export class FillTableFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: FillTableFunctionProps) {
    super(scope, id, {
      description: 'src/Construct/lambda/fillTable.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs22.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/Construct/lambda/fillTable.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}
